### ISSUE TITLE
Unable to create new organization

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#141]
After filling out the fields, clicking on the add new button does nothing.

**Comment by jcaraballo17** [comment]
There was a problem with the https protocol and the web service endpoint that adds the new organizations. It's fixed now.

**Comment by SRGDamia1** [comment]
Okay.  It seems to be fixed on sandbox, but is still not working on production.  Also, there are two organizations that seem like obvious junk and should be removed:  "name" and "new organization or whatever."

**Comment by jcaraballo17** [comment]
The sandbox didn't have that problem, the secure connection was only implemented in production. The fix didn't have anything to do with the code, so I fixed it in production and it works as expected here. 
I created those organizations (and a new one just right now) to test it was working. I'm going to delete those in a few minutes. 

I can't reproduce this error anymore. Can you give me the information you're writing in the form? Maybe if I fill it out with the same data I'll have the same problem.

**Comment by horsburgh** [comment]
@SRGDamia1 - I cleared my browser cache and added USU as an organization and it worked for me. The testing organizations are gone as well.

**Comment by horsburgh** [comment]
@SRGDamia1 - by the way, we will not be updating the sandbox until the next release, so no need to test on the sandbox for the moment. If you can clear your browser cache and try again, I think this one can be closed.

**Comment by SRGDamia1** [comment]
I just got it to work.  Thank you!

**Comment by SRGDamia1** [comment]
Okay, I lied, it's not fixed.  I can create a new organization when creating a new user, but I cannot create a new organization when trying to update the organization for an existing user.

**Comment by aufdenkampe** [comment]
What's our status with this? Have the v0.4.5 fixes all been deployed to Production?

I'm wondering if we can issue the v0.4.5 Release and close the [0.4.5 Bug Fixes Milestone](https://github.com/ODM2/ODM2WebSDL/milestone/8).

**Comment by jcaraballo17** [comment]
The code fixes have been already deployed. I am working on this issue right at this moment and will have it fixed soon. After making sure we don't have this problem anymore we can close this milestone and test milestone 0.5

**Comment by jcaraballo17** [comment]
We'll update the whole site to be used over https at some point in the future, but right now we can't have only some pages use https while sharing the same web services. I've reverted everything to work over http. You can test creating a new organization from both the sign up and the account pages before closing this issue.

**Comment by horsburgh** [comment]
@jcaraballo17 - did you make these changes on production? Should they test on production?

**Comment by horsburgh** [comment]
I'm assuming this has now been resolved on production, so closing.
