### ISSUE TITLE
Sort "instrument raw output unit" in the dropdown

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#190]
![capture](https://user-images.githubusercontent.com/5374350/36868600-d50be71a-1d66-11e8-9da4-d964efd3134d.JPG)

In the admin panel.  Please make it alphabetical.

**Comment by SRGDamia1** [comment]
Oh, it's alphabetical by abbreviation.  That's fine, as long as the unit and type get separated (#191)

**Comment by aufdenkampe** [comment]
Either way, I think sorting by the unit term or name is much more preferable than sorting by the unit abbreviation, which is often case sensitive and doesn't include enough letters for a logical sort.

**Comment by jcaraballo17** [comment]
Changed the text that appears in the units dropdown (both in the admin and the webpage). 
It is now sorted by the units name while still displaying the abbreviation and units type.

![image](https://user-images.githubusercontent.com/4700505/50299891-2623ed80-0459-11e9-9e27-3c04efe87046.png)

**Comment by SRGDamia1** [comment]
I don't see the fix on staging, but it seems ok on the live site.

**Comment by aufdenkampe** [comment]
@SRGDamia1, yes, this is fixed on production but not on staging.
@jcaraballo17, can you look at what might have happened?

**Comment by jcaraballo17** [comment]
This wasn't fixed on production. Because of the `units_type: units_name (units_abbreviation)` format the text had, it was all ordered by `units_type`. In December I changed that format, but didn't change the ordering.

The dropdowns are now ordered by `units_name` and with the latest format it looks like this:
![image](https://user-images.githubusercontent.com/4700505/62327952-d2ae5f00-b47f-11e9-9660-9cc2bf9153c0.png)

**Comment by aufdenkampe** [comment]
@jcaraballo17, this looks great, and the filtering is very nice!
