### ISSUE TITLE
Fix bug. New variables added via Admin not available to sensors

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#292]
I just use the Admin panel to add this new instrument output variable: `MaxBotix_MB7389_GageHeight measured in mm`
http://data.envirodiy.org/admin/dataloader/instrumentoutputvariable/329/change/

However, it is not available on the front end when adding a new sensor/variable.
This used to work, as I've done it many times.

@jcaraballo17, @Maurier and @horsburgh. Any ideas?

**Comment by jcaraballo17** [comment]
@aufdenkampe Yes! In milestone 0.8 we had [this issue](https://github.com/ODM2/ODM2DataSharingPortal/issues/158) for linking a sensor/variable to a specific sampled medium. http://data.envirodiy.org/admin/dataloaderinterface/sensoroutput/add/ this form is the one that works for adding new sensors.
Sorry for the confusion, I realize I never stated that explicitly in the issue tracker.

**Comment by aufdenkampe** [comment]
@jcaraballo17, thanks for pointing me to that new capability & requirement when adding sensors. I vaguely remember seeing issue https://github.com/ODM2/ODM2DataSharingPortal/issues/158 when @SRGDamia1 posted it and when it was put on the `back burner`.  However, I don't remember at all the discussion to take it off the `back burner`. In fact, although I see some potential benefit for the user, I see it as an additional complicated layer for us managers. Oh well. Thanks for the pointer. I'll work sorting out my issue.

**Comment by aufdenkampe** [comment]
@jcaraballo17, I'm getting `Server Error (500)` when I try to do this for:

- Equipment Model: MB7389 HRXL-MaxSonar-WRMT
- Variable: MaxBotix_MB7389_GageHeight
- Unit: Length: Millimeter
- Sampled Medium: Liquid aqueous

So are we still using "Instrument Output Variable", which incorporates all of the above except Medium.
Is this possibly connected to why I'm getting a server error?

**Comment by horsburgh** [comment]
I was able to verify that this works on the sandbox. I had to do the following:
1. Click on the "Admin" link to enter Admin mode
2. Click on the "Equipment models" link to verify the equipment model exists. If not, add it. (in my test, using the information in @aufdenkampe 's example above, the equipment model already existed)
3. Go back to the main admin menu and click on the "Variables" link to add the variable. I used the info above to create a new variable for Gage height.
4. Go back to the main admin menu and click on the "Instrument output variables" link. Added an instrument output variable to link the variable to the equipment model. 

Once I had successfully run these steps, I was able to get all of this to show up on the Add New Sensor form. I'm adding the "tested" label to this one.

**Comment by aufdenkampe** [comment]
This isn't yet really working, because the front end "Add New Sensor" modal window still filters the "Medium" based on some association with the sensor or variable.  Try it for my example in https://github.com/ODM2/ODM2DataSharingPortal/issues/292#issuecomment-420439221. This filtering needs to be turned off.

@horsburgh, thanks for fulling testing the Django Admin mode. That part looks good to me too.

**Comment by horsburgh** [comment]
@aufdenkampe - I'm not seeing this. On the front end, I can select the manufacturer, Sensor Model, Measured Variable, and Units. Once I do this, all of the sampled media are available for selection. Am I missing something?

![image](https://user-images.githubusercontent.com/3485902/47885597-7983a300-ddfb-11e8-8f01-aded2910b7d9.png)

**Comment by jcaraballo17** [comment]
Oops. @aufdenkampe I forgot to update the filtering in the sandbox database for the old data. I'll update that as soon as I can.
The issue addressed here with adding new variables with the django admin is fixed, and by selecting those new variables you get all sampled mediums as options, right?

**Comment by aufdenkampe** [comment]
@horsburgh thanks for the feedback.

Unfortunately, I just retested this on both Chrome and Safari after refreshing the cache, and I still see an issue for the first MaxBotix sensor, MB7386. However, it no longer is an issue on the second one. This was also the case for different sites.

@jcaraballo17, does that make sense with what you just noticed?

**Comment by jcaraballo17** [comment]
@aufdenkampe Just finished running a script for updating that data in the database. 
It should be working now.

**Comment by horsburgh** [comment]
@aufdenkampe - thanks for testing this. I just went through and sampled a bunch of sensors on the "Add New Sensor" form, and since Juan ran his update script, all of the Sampled Media are available for all of the sensors I tried. I'm going to add the "tested" label to this one again.

**Comment by aufdenkampe** [comment]
Great! It works for me!
