### ISSUE TITLE
Sensor/data added but can't view in time series analyst - it just spins

### ISSUE THREAD

**Issue by dbressler75** [ODM2/ODM2DataSharingPortal#378]
Once new sensor added/data uploaded still can't view in Time Series Analyst and it indicates 0 data points.  The data are there as seen in the table download but the time series analyst won't work (it just spins in Visualization) and in Datasets tab it indicates 0 Number Observations.

**Comment by aufdenkampe** [comment]
Thanks, there's clearly an issue with the connection to the InfluxDB database that Time Series Analyst (TSA) uses. This has happened before.

**Comment by aufdenkampe** [comment]
This appears to have been fixed along with #390.

@dbressler75, can you confirm? If it doesn't work, can you share the site ID and variable with us, as these are critical to sleuthing out the issues.

**Comment by aufdenkampe** [comment]
@dbressler75, Reopen if this continues to be an issue.

**Comment by SRGDamia1** [comment]
@aufdenkampe It's still broken.

See:  http://www.monitormywatershed.org/tsa/?sitecode=4GBee_Transparent&view=datasets&plot=false and http://data.envirodiy.org/sites/4GBee_Transparent/

I still suspect that it is related to the WOFpy issue (#379) because - as you see in the datasets view - TSA thinks there are no points available for the dataset and there's an endless spin waiting for the graph.  

For a site that had data prior to January 31, 2019, you can see the plots and all the data is there.  I don't think those site were ever broken.

That's why I think TSA must still be getting the index of the database from WOFpy, not from influx (even though it gets the data itself from influx).  And then it won't even attempt to plot if it thinks there are 0 values.  Also notice how if you look at all the datasets in TSA, a huge number of them have their "last updated" date on January 31 or a bit earlier.  For a lot of those site, if you were to look at the plot, you would actually see data up until today.

**Comment by aufdenkampe** [comment]
@SRGDamia1, thanks for pointing me to this site! This really helps us understand the issue. And it also make sense for this station, because it was registered on May 1.

As I mentioned in https://github.com/ODM2/ODM2DataSharingPortal/issues/379#issuecomment-493229973, the `tsa_catalog` gets populated from the `ODM2` schema, both in PostgreSQL, from a Django script. And all of that was definitely broken in recent weeks. So we'll get on it.

**Comment by jcaraballo17** [comment]
Here's a description of the problem from January 31st on Slack:

> The script that generates the TSA Catalog table uses the 'tsa_catalog' database connection info in settings.json for generating the URLs the website uses to get the data. Right now, that connection data in settings.json file has the private internal IP address, so changing that IP address to the public one and rebuilding the TSA catalog fixed the problem.
> *BUT* the script can't connect to `dbs.monitormywatershed.org`. It appears as if the public IP address is not accessible to the limnotech private network.

This fixed the problem because when the catalog is generated, it takes the `tsa_catalog` server address (the database/influx server) and uses it for building each series' InfluxDB URL. Those URLs are used to retrieve the InfluxDB data from the web browser by the TSA, so that server address needs to the public one.  But the web server can't connect to the database server through the public address.

It seems like the script to re-generate the TSA Catalog was run again after this fix, and all the InfluxDB URLs now contain the internal ip address again. This makes the TSA not able to load the data, because it's trying to connect to a private ip address to get the series data.

**Comment by jcaraballo17** [comment]
Instead of using the database server address, I added a new entry on the file `settings.json` named `influx_server`. This new entry contains the public domain name `dbs.monitormywatershed.org`, so that the `rebuild_tsa_catalog` script no longer has a dependency on the database server's internal IP address.

The hotfix can be seen on this pull request:
https://github.com/ODM2/ODM2DataSharingPortal/pull/394

**Comment by jcaraballo17** [comment]
Tested this by plotting series on the TSA.
Adding `close me` tag.

**Comment by aufdenkampe** [comment]
@jcaraballo17, thank you for providing those explanations of the fix, and for applying it as a hot fix!
